


WIDTH = 720
HEIGHT = 720
FPS = 60

KEY = 5829

FONT_SIZE = 70
FONT_COLOR = (0, 0, 0)
TEXT_OFFSET = 140

BC_ART = 'art/bc/bc_transparent.png'

GRID_SIZE = 525
TOP_PLUS_OFFSET = 50
TOP_OFFSET = HEIGHT / 2 - GRID_SIZE / 2 + TOP_PLUS_OFFSET
LEFT_OFFSET = WIDTH / 2 - GRID_SIZE / 2

TILE_SIZE = 100
TILE_GAP = 25
TILE_ANIM_LENGTH = 3
TILE_ANIM_SPEED = 1

SAVE_DIRECT = 'saves/save_data.txt'
